language: java
jdk:
  - openjdk8
os:
  - linux
cache:
  directories:
    - ~/.m2/repository
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --quiet --batch-mode --show-version
script:
  - mvn package --batch-mode --show-version
